# Generated by Django 4.0.4 on 2022-04-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='star_time',
            new_name='start_time',
        ),
    ]
