# Generated by Django 4.0.4 on 2022-06-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0003_activity_timelog_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
