# Generated by Django 4.0.4 on 2022-07-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0006_userproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='token',
            new_name='api_key',
        ),
        migrations.AddField(
            model_name='profile',
            name='api_secret',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
