# Generated by Django 4.0.4 on 2022-10-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0008_profile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='employee_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='employee_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
