# Generated by Django 4.0.4 on 2022-10-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0009_profile_employee_id_profile_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='actual_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='task',
            name='expected_time',
            field=models.FloatField(default=0.0),
        ),
    ]
