# Generated by Django 4.0.4 on 2022-12-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0011_project_erp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
