# Generated by Django 4.0.4 on 2023-01-06 15:34

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_alter_preferences_id'),
        ('timesheet', '0012_project_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesheetPreferences',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.preferences')),
                ('admin_token', models.CharField(default='', max_length=200)),
            ],
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
    ]
