# Generated by Django 4.0.4 on 2023-01-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0013_timesheetpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetpreferences',
            name='map_api_key',
            field=models.CharField(default='', max_length=200),
        ),
    ]
