# Generated by Django 4.0.4 on 2023-01-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0014_timesheetpreferences_map_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
