# Generated by Django 4.0.4 on 2023-02-05 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timesheet', '0016_clock_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug_name', models.SlugField(blank=True, max_length=256, null=True)),
                ('active', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('chart_data', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheet.project')),
            ],
        ),
    ]
