# Generated by Django 4.0.4 on 2023-09-01 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0022_alter_timelog_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='timesheet.timelog'),
        ),
    ]
