# Generated by Django 4.0.4 on 2023-09-01 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0023_timelog_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='timesheet.timelog'),
        ),
    ]
