# Generated by Django 4.0.4 on 2023-12-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0027_task_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetpreferences',
            name='unavailable_dates',
            field=models.TextField(blank=True, default='', help_text='Enter the dates when timesheet submission is not available, separated by commas. E.g., "2023-12-24,2023-12-25". On these dates, users will not be able to submit timesheet.'),
        ),
    ]
