# Generated by Django 4.1.9 on 2024-11-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0029_projectlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlink',
            name='category',
            field=models.CharField(blank=True, choices=[('DOC', 'Documentation'), ('CHA', 'Chat'), ('REP', 'Repository'), ('DIA', 'Diagram')], max_length=3),
        ),
    ]
