# Generated by Django 5.2.7 on 2026-02-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheet", "0030_projectlink_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelog",
            name="is_paused",
            field=models.BooleanField(default=False, help_text="Timesheet is paused"),
        ),
    ]
