# Generated by Django 5.2.7 on 2026-02-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheet", "0031_add_is_paused_to_timelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="erpnext_oauth_access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="erpnext_oauth_refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="erpnext_oauth_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
