# Generated by Django 5.2.7 on 2026-02-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheet", "0032_add_erpnext_oauth_fields_to_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="is_billable",
            field=models.BooleanField(default=False),
        ),
    ]
