    # Generated by Django 5.2.7 on 2026-03-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheet", "0033_add_is_billable_to_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("INTERNAL", "Internal"),
                    ("EXTERNAL", "External"),
                    ("INVESTMENT", "Investment"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
