# Generated by Django 5.2.14 on 2026-05-18 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo_dashboard', '0001_initial'),
        ('timesheet', '0034_project_project_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pmo_dashboard.businessunit'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External'), ('INVESTMENT', 'Investment')], default='', max_length=100),
        ),
    ]
