# Generated by Django 5.2.14 on 2026-05-25 14:16

import timesheet.models.preferences
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timesheet", "0035_project_actual_time_project_business_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheetpreferences",
            name="pmo_status_config",
            field=models.JSONField(
                default=timesheet.models.preferences.get_default_pmo_status_config,
                help_text="Configurable PMO status labels and formulas. Keys are fixed: on_track, warning, at_risk, overdue, on_hold, completed.",
            ),
        ),
    ]
