# Generated by Django 5.2.14 on 2026-05-26 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('timesheet', '0036_timesheetpreferences_pmo_status_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetpreferences',
            name='pmo_allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups allowed to access the PMO Dashboard.', related_name='pmo_allowed_preferences', to='auth.group'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='auth.group')),
            ],
            options={
                'ordering': ['erp_id'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='timesheet.department'),
        ),
    ]
