# Generated by Django 5.2.14 on 2026-05-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0037_alter_projectmember_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='project_lead',
            field=models.BooleanField(default=False),
        ),
    ]
