# Generated by Django 5.2.14 on 2026-06-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0037_add_department_and_pmo_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetpreferences',
            name='pm_overload_threshold',
            field=models.PositiveSmallIntegerField(default=4, help_text='Number of active projects above which a Project Manager is considered overloaded in the workload chart.'),
        ),
    ]
