# Generated by Django 5.2.14 on 2026-06-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0037_add_department_and_pmo_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
