# Generated by Django 5.2.14 on 2026-06-17 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0038_add_last_synced_at_to_project'),
        ('timesheet', '0038_add_pm_overload_threshold'),
    ]

    operations = [
    ]
