# Generated by Django 5.2.14 on 2026-06-30 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0040_timesheetpreferences_is_updating'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='billable_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
