# Generated by Django 5.2.14 on 2026-07-20 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0041_add_billable_hours_to_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheetpreferences',
            name='sprint_review_anchor',
            field=models.DateField(default=datetime.date(2026, 7, 24), help_text='A known sprint-review Friday. Reviews happen every 14 days on this weekday; used to compute "last sprint" boundaries for the Support Dashboard. Update if the sprint schedule ever shifts.'),
        ),
    ]
