# Generated by Django 5.2.14 on 2026-07-28 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0042_timesheetpreferences_erp_admin_user'),
        ('timesheet', '0042_timesheetpreferences_sprint_review_anchor'),
    ]

    operations = [
    ]
