# Generated by Django 5.2.15 on 2026-08-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0043_merge_20260728_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='erp_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Name of the Timesheet Detail row this log was imported from. Empty for logs tracked in this app.', max_length=255),
        ),
    ]
