# Generated by Django 4.0.4 on 2023-03-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprojectslot',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='userprojectslot',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
