# Generated by Django 4.0.4 on 2023-03-10 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0017_savedsummary'),
        ('schedule', '0002_alter_userprojectslot_options_userprojectslot_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timesheet.task'),
        ),
    ]
