# Generated by Django 4.0.4 on 2023-03-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0017_savedsummary'),
        ('schedule', '0003_schedule_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('name', models.CharField(max_length=256)),
                ('slug_name', models.SlugField(blank=True, max_length=256, null=True)),
                ('active', models.BooleanField(default=True)),
                ('view_count', models.IntegerField(default=0)),
                ('projects', models.ManyToManyField(blank=True, null=True, to='timesheet.project')),
            ],
        ),
    ]
