# Generated by Django 4.0.4 on 2023-03-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0018_task_last_update'),
        ('schedule', '0004_publictimeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publictimeline',
            name='projects',
            field=models.ManyToManyField(blank=True, to='timesheet.project'),
        ),
    ]
