# Generated by Django 4.0.4 on 2023-03-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_alter_publictimeline_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='first_day_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='hours_per_day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='last_day_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
