# Generated by Django 4.0.4 on 2023-04-11 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0019_alter_task_last_update'),
        ('schedule', '0006_schedule_first_day_number_schedule_hours_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='timesheet.activity'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.userprojectslot'),
        ),
    ]
