# Generated by Django 4.0.4 on 2023-04-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_schedule_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='erp_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
