# Generated by Django 4.0.4 on 2023-08-08 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0019_alter_task_last_update'),
        ('schedule', '0009_schedule_erp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timesheet.task'),
        ),
    ]
