# Generated by Django 5.2.7 on 2026-04-21 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0002_post_period_range'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledPostConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Human-readable label for this feed', max_length=200)),
                ('rss_url', models.URLField(help_text='RSS feed URL to fetch posts from')),
                ('post_type', models.CharField(choices=[('default', 'Default'), ('announcement', 'Announcement'), ('tips', 'Tips'), ('question', 'Question'), ('warning', 'Warning'), ('celebration', 'Celebration')], default='default', help_text='Type assigned to every post created from this feed', max_length=32)),
                ('posts_per_day', models.PositiveIntegerField(default=1, help_text='Maximum number of posts to publish per day from this feed')),
                ('display_duration_hours', models.PositiveIntegerField(default=24, help_text='How many hours each post stays visible (sets period_end)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, help_text='When this feed was last successfully fetched', null=True)),
                ('last_item_guid', models.CharField(blank=True, help_text='GUID of the most recently published RSS item — used to avoid duplicates', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='User account used as the post author', on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_post_configs', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, help_text='Tags automatically added to every post created from this feed', related_name='scheduled_post_configs', to='microblog.tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
