# Generated by Django 5.2.14 on 2026-07-16 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo_dashboard', '0001_initial'),
        ('timesheet', '0041_add_billable_hours_to_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('sla_type', models.CharField(blank=True, choices=[('SLA', 'SLA'), ('HOSTING', 'Hosting')], default='', max_length=20)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_tracker', to='timesheet.project')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erp_id', models.CharField(max_length=64, unique=True)),
                ('subject', models.CharField(blank=True, default='', max_length=512)),
                ('raised_by', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(blank=True, default='', max_length=32)),
                ('priority', models.CharField(blank=True, default='', max_length=32)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('is_internal', models.BooleanField(default=False, help_text='True if project is unset or the linked project is internal.')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='timesheet.project')),
            ],
            options={
                'ordering': ['-opening_date'],
            },
        ),
    ]
