# Generated by Django 5.2.14 on 2026-07-17 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo_dashboard', '0001_initial'),
        ('timesheet', '0041_add_billable_hours_to_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('sla_type', models.CharField(blank=True, choices=[('SLA', 'SLA'), ('HOSTING', 'Hosting')], default='', max_length=20)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_tracker', to='timesheet.project')),
            ],
        ),
    ]
