# Generated by Django 5.2.14 on 2026-07-20 12:28
"""Also seeds SupportContactMapping from the legacy Support_report spreadsheet
formula. Customer values were cross-checked against locally synced
Project.customer values where a matching project existed, so entries merge
cleanly with the Project-based resolution path (see _resolve_issue_customer in
timesheet/utils/erp.py) instead of duplicating a bucket under a different
label. A few entries (GGCITY, GSH) had no matching local project and keep the
original spreadsheet label.
"""

from django.db import migrations, models

SADC_GMI = 'Southern Africa Development Community – Groundwater Management Institute (SADC-GMI)'
UMVOTO = 'Umvoto Africa (Pty) Ltd'
PARATUS = 'Paratus Telecommunications (Pty) Ltd'
GIZ = 'Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ)'

SEED_ROWS = [
    # Project-name override: GSH Support's own `customer` field is 'Kartoza'
    # (it's a shared/internal intake project), not a useful reporting bucket.
    {'project_name': 'GSH Support', 'email': '', 'customer': 'GSH'},

    {'email': 'jamesm@sadc-gmi.org', 'customer': SADC_GMI},

    {'email': 'claudia.ruz-vargas@un-igrac.org', 'customer': 'UN-IGRAC'},
    {'email': 'elie.gerges@un-igrac.org', 'customer': 'UN-IGRAC'},
    {'email': 'arnaud.sterckx@un-igrac.org', 'customer': 'UN-IGRAC'},
    {'email': 'enrico.boldrini@cnr.it', 'customer': 'UN-IGRAC'},
    # deepti@pegasys.co.za was bucketed as 'SADC-GIP' in the old spreadsheet, but
    # every matching SADC-GIP-* project in ERPNext is actually customer=UN-IGRAC.
    {'email': 'deepti@pegasys.co.za', 'customer': 'UN-IGRAC'},

    {'email': 'eddie.w@umvoto.com', 'customer': UMVOTO},
    {'email': 'tyrel.f@umvoto.com', 'customer': UMVOTO},

    {'email': 'vanderlaanm@arc.agric.za', 'customer': 'University of Pretoria'},

    {'email': 'avandenberg@landinfotech.com', 'customer': 'LandInfo Technologies Inc'},

    {'email': 'AlgoaBayProject@mandela.ac.za', 'customer': 'Nelson Mandela University'},
    {'email': 'victoriagoodall@gmail.com', 'customer': 'Nelson Mandela University'},

    # No matching local project for GGCITY; keep the original spreadsheet label.
    {'email': 'nicolaso@ggcity.org', 'customer': 'GGCITY'},

    {'email': 'sysdev.na@paratus.africa', 'customer': PARATUS},
    {'email': 'cobus.burger@paratus.africa', 'customer': PARATUS},

    {'email': 'walter.mogajana@sanparks.org', 'customer': 'Freshwater Research Centre'},

    {'email': 'maabbanani@gmail.com', 'customer': 'IHE Delft'},

    {'email': 'andresfelipe.ramirez@giz.de', 'customer': GIZ},
    {'email': 'dirk.euler@giz.de', 'customer': GIZ},
    {'email': 'gunnar.hesch@giz.de', 'customer': GIZ},

    # 'Rest' branch: known internal/test contacts, explicitly excluded (blank customer).
    {'email': 'voogt001@gmail.com', 'customer': ''},
    {'email': 'dylanpivo@gmail.com', 'customer': ''},
    {'email': 'otto@netexec.co.za', 'customer': ''},
    {'email': 'idletech@astound.net', 'customer': ''},
    {'email': '@kartoza.com', 'customer': '', 'note': 'Domain wildcard: internal Kartoza staff'},
    {'email': '@test.com', 'customer': '', 'note': 'Domain wildcard: test accounts'},
]


def seed_mapping(apps, schema_editor):
    SupportContactMapping = apps.get_model('pmo_dashboard', 'SupportContactMapping')
    for row in SEED_ROWS:
        SupportContactMapping.objects.get_or_create(
            email=row.get('email', ''),
            project_name=row.get('project_name', ''),
            defaults={
                'customer': row.get('customer', ''),
                'note': row.get('note', ''),
            },
        )


def unseed_mapping(apps, schema_editor):
    SupportContactMapping = apps.get_model('pmo_dashboard', 'SupportContactMapping')
    keys = [(row.get('email', ''), row.get('project_name', '')) for row in SEED_ROWS]
    for email, project_name in keys:
        SupportContactMapping.objects.filter(email=email, project_name=project_name).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pmo_dashboard', '0003_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportContactMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', help_text="Full email address, or '@domain.com' for a domain-wide match. Leave blank if using project_name.", max_length=256)),
                ('project_name', models.CharField(blank=True, default='', help_text="ERPNext Project name to override, taking priority over that Project's own customer field. Leave blank if using email.", max_length=512)),
                ('customer', models.CharField(blank=True, default='', help_text='Customer bucket to assign (matches Project.customer values). Blank = explicitly internal/excluded.', max_length=256)),
                ('note', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'ordering': ['project_name', 'email'],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='customer',
            field=models.CharField(blank=True, default='', help_text='Resolved customer bucket, used for Support Dashboard grouping.', max_length=256),
        ),
        migrations.AlterField(
            model_name='issue',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='True if no customer could be resolved, or the resolved customer is explicitly internal.'),
        ),
        migrations.RunPython(seed_mapping, unseed_mapping),
    ]
