# Generated by Django 5.2.14 on 2026-07-20 12:28
"""Also seeds SupportContactMapping from an external, gitignored JSON file
(support_contact_mapping_seed.json in this app's directory) rather than
hardcoding real client contacts in a migration that ships in a public repo.

See support_contact_mapping_seed.example.json for the expected row format,
and DEPLOY.md for how to place the real file in production before running
this migration. If the file is missing, seeding is skipped entirely (the
table is simply left empty) so the migration still applies cleanly.
"""

import json
from pathlib import Path

from django.db import migrations, models

SEED_FILE = Path(__file__).resolve().parent.parent / 'support_contact_mapping_seed.json'


def _load_seed_rows():
    if not SEED_FILE.exists():
        return []
    with open(SEED_FILE) as f:
        return json.load(f)


def seed_mapping(apps, schema_editor):
    SupportContactMapping = apps.get_model('pmo_dashboard', 'SupportContactMapping')
    for row in _load_seed_rows():
        SupportContactMapping.objects.get_or_create(
            email=row.get('email', ''),
            project_name=row.get('project_name', ''),
            defaults={
                'customer': row.get('customer', ''),
                'note': row.get('note', ''),
            },
        )


def unseed_mapping(apps, schema_editor):
    SupportContactMapping = apps.get_model('pmo_dashboard', 'SupportContactMapping')
    keys = [(row.get('email', ''), row.get('project_name', '')) for row in _load_seed_rows()]
    for email, project_name in keys:
        SupportContactMapping.objects.filter(email=email, project_name=project_name).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pmo_dashboard', '0003_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportContactMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', help_text="Full email address, or '@domain.com' for a domain-wide match. Leave blank if using project_name.", max_length=256)),
                ('project_name', models.CharField(blank=True, default='', help_text="ERPNext Project name to override, taking priority over that Project's own customer field. Leave blank if using email.", max_length=512)),
                ('customer', models.CharField(blank=True, default='', help_text='Customer bucket to assign (matches Project.customer values). Blank = explicitly internal/excluded.', max_length=256)),
                ('note', models.CharField(blank=True, default='', max_length=256)),
            ],
            options={
                'ordering': ['project_name', 'email'],
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='customer',
            field=models.CharField(blank=True, default='', help_text='Resolved customer bucket, used for Support Dashboard grouping.', max_length=256),
        ),
        migrations.AlterField(
            model_name='issue',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='True if no customer could be resolved, or the resolved customer is explicitly internal.'),
        ),
        migrations.RunPython(seed_mapping, unseed_mapping),
    ]
