# Generated by Django 5.2.14 on 2026-08-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmo_dashboard', '0004_supportcontactmapping_issue_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Replied', 'Replied'), ('On Hold', 'On Hold'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='', max_length=32),
        ),
    ]
